### PR TITLE
Optimized convert_data_frame_to_matrix() function

### PR DESCRIPTION
**Pull request by arko-bhattacharya**
Optimized convert_data_frame_to_matrix() function for discontinuous dense matrices per ticket #99. However, performance might deteriorate for continuous dense matrix in which case ideas from the current method will have to be used along with the prior method.

### CODE REVIEW

**Comment by ksens** [comment]
Great! Will run the benchmark script on deployment A to see overall performance.

**Comment by ksens** [comment]
@arko-bhattacharya 

Made a few edits (see commits above). 

I have started the data collection at deployment A -- should have results in a day. 

In the meantime, please try to do the data collection comparing current `master` and this PR's branch on TCGA demo machine. Since that machine mostly contains continuous dense matrices, it should give a great idea of the degradation in performance (if any) due to the extra checks.

**Comment by ksens** [comment]
@arko-bhattacharya 

Calling this version of the optimizations `dte_v4` for reference sake. Sharing my summary here:

## Deployment A
Here are the results at deployment A:

### Towards the larger download sizes for RNA-seq

image

Size marker is at 1345 Mb. Plot size starts at ~100 Mb.

### Medium download size

image

Size marker is at 29 Mb. 

### And now from small to medium download size

image

Size marker is at 14 Mb (starts from ~2-3 Mb)

## Summary

New set of optimizations

- introduce 0.5-1 seconds of delay for small sized data (2-10 Mb)
- transitions to being ~1 second faster at medium sized data (around 20 Mb)
- are generally faster starting around 100 Mb
- at large sizes (~1000 Mb)
     - saves ~70-80 seconds for dense discontinuous / dense continuous case
     - adds ~20 seconds for sparse case (quite possibly, due to the extra sorting)

Overall, the new set of optimizations seems to have a net positive impact (given that large sparse matrices with a handful of sparse values are the exception). I will merge in this PR. 

Any future developments on this work should be done on a new branch. 

PS: In case it is needed, here is how you can export plotly plots as a fully interactive HTML file:

image

**Comment by ksens** [comment]
@arko-bhattacharya 

Do paste in the results from the demo machine when you get a chance. Merging PR for now.

**Comment by ksens** [comment]
Archiving HTML from deployment A for reference. 
[deploymentA_revealgenomics_pr108_results.zip](https://github.com/Paradigm4/revealgenomics/files/3573578/deploymentA_revealgenomics_pr108_results.zip)

**Comment by arko-bhattacharya** [comment]
Here are the benchmarking plots from the demo machine. In these plots 'master' refers to the latest optimizations in convert_data_frame_to_matrix() for discontinuous dense matrices. This is referred to as 'dte_v4' in the above plots. The earlier set of optimizations for continuous dense matrices are referred to as 'dt_enhancements_v2'.

Performance plot for search_expression() -
runTime-20190904-search_expression-myOptim-vs-dtEncV2

Performance plot for search_biosamples() -
runTime-20190904-search_biosamples-myOptim-vs-dtEncV2

We can see that both the versions perform similary as these performance numbers are based on TGCA data-sets which are continuous dense matrics.

**Pull request merged**
